# Update debian repo
---
- name: Update APT package cache
  apt: update_cache=yes cache_valid_time=3600

- name: Get aptitude for upgrade
  apt: pkg=aptitude state=present
  
- name: Upgrade APT to the latest packages
  apt: upgrade=safe

- name: Adjust APT update intervals
  copy: src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic

- name: Install unattended upgrades
  package: state=present name=unattended-upgrades
